project:
  type: website
  output-dir: docs

website:
  title: "Tahsin Khan"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: authoring/index.qmd
        text: "Projects"
      - href: post/
        text: Posts
      - href: about.qmd
        text: About
    
    right:
      - icon: bluesky
        href: https://bsky.app/profile/tahsinkhann.bsky.social
        target: _blank
        rel: noopener
      - icon: linkedin
        href: https://www.linkedin.com/in/tahsinkhann
        target: _blank
        rel: noopener
  bread-crumbs: false
  back-to-top-navigation: true

    
        

format: 
  html:
    theme: cosmo
    toc: true
    link-external-newwindow: true
    

bibliography: 
  - references.bib


csl: styles/nature.csl
