project: 
  type: default
  output-dir: ..
  
render:
  - index.qmd
  - people.qmd
  - published_articles.qmd
  

execute: 
  echo: false
  warning: false
  message: false

format: 
  gfm: 
    variant: +yaml_metadata_block
    raw-html: true




